# Generated by Django 4.1 on 2022-10-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flux", "0006_alter_review_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="is_reviewed",
            field=models.BooleanField(default=False),
        ),
    ]
