# Generated by Django 4.1 on 2022-10-18 19:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("follower", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="follow", unique_together={("user", "followed_user")},
        ),
    ]
